const CarDetailData = [
    {
      idx:"1",
      model: "Model X",
      Delivery: "Jul - Aug 2023",
      img:{
        img1:"teslaCar1.jpg",
        img2:"teslaCar2.jpg",
        img3:"teslaCar3.jpg",
        img4:"teslaCar4.jpg",
        img5:"teslaCar5.jpg",
      },
      range: "348",
      speed: "149",
      mph: "3.8",
      dualMotorPrice: "98,490",
      triMotorPrice: "108,490",
    },
    {
      idx:"2",
      model: "Model Y",
      Delivery: "Jul - Aug 2023",
      img:{
        img1:"teslaCarY1.jpg",
        img2:"teslaCarY2.jpg",
        img3:"teslaCarY3.jpg",
        img4:"teslaCarY4.jpg",
        img5:"teslaCar5.jpg",
      },
      range: "330",
      speed: "135",
      mph: "4.8",
      dualMotorPrice: "47,740",
      triMotorPrice: "54,490",
    },
    {
      idx:"3",
      model: "Model 3",
      Delivery: "Jul - Aug 2023",
      img:{
        img1:"teslaCar3-1.jpg",
        img2:"teslaCar3-2.jpg",
        img3:"teslaCar3-3.jpg",
        img4:"teslaCar3-4.jpg",
        img5:"teslaCar5.jpg",
      },
      range: "272",
      speed: "140",
      mph: "5.8",
      dualMotorPrice: "40,490",
      triMotorPrice: "53,490",
    },
    {
      idx:"4",
      model: "Model S",
      Delivery: "Jul - Aug 2023",
      img:{
        img1:"teslaCarS1.jpg",
        img2:"teslaCarS2.jpg",
        img3:"teslaCarS3.jpg",
        img4:"teslaCarS4.jpg",
        img5:"teslaCar5.jpg",
      },
      range: "405",
      speed: "149",
      mph: "3.1",
      dualMotorPrice: "88,490",
      triMotorPrice: "108,490",
    },
  ];

  const carData = [
    {
      idx:"5",
      title: "Experience Tesla",
      description: "Schedule a Demo Drive Today",
      backgroundImg: "",
      backgroundVideo: "./videos/HomeVideo.webm",
      leftBtnText: "Demo Drive",
      rightBtnText:"",
    },
    {
      idx:"4",
      title: "Model S",
      description: "Order Online for Touchless Delivery",
      backgroundVideo: "",
      backgroundImg: "model-s.jpg",
      leftBtnText: "Custom Order",
      rightBtnText: "Existing Inventory",
    },
    {
      idx:"2",
      title: "Model Y",
      description: "Starting at $40,240 After Federal Tax Credit",
      backgroundVideo: "",
      backgroundImg: "model-y.jpg",
      leftBtnText: "Custom Order",
      rightBtnText: "Existing Inventory",
    },
    {
      idx:"3",
      title: "Model 3",
      description: "Starting at $32,740 After Federal Tax Credit",
      backgroundVideo: "",
      backgroundImg: "model-3.jpg",
      leftBtnText: "Custom Order",
      rightBtnText: "Existing Inventory",
    },
    {
      idx:"1",
      title: "Model X",
      description: "Order Online for Touchless Delivery",
      backgroundVideo: "",
      backgroundImg: "model-x.jpg",
      leftBtnText: "Custom Order",
      rightBtnText: "Existing Inventory",
    },
    {
      idx:"6",
      title: "Solar Panels",
      description: "Schedule a Virtual Consultation",
      backgroundVideo: "",
      backgroundImg: "solar-panel.jpg",
      leftBtnText: "Order Now",
      rightBtnText: "Learn More",
    },
    {
      idx:"7",
      title: "Solar Roofs",
      description: "Produce Clean Energy From Your Roof",
      backgroundVideo: "",
      backgroundImg: "solar-roof.jpg",
      leftBtnText: "Order Now",
      rightBtnText: "Learn more",
    },
    {
      idx:"8",
      title: "Powerwall",
      description: "",
      backgroundVideo: "",
      backgroundImg: "powerwall.jpeg",
      leftBtnText: "Order Now",
      rightBtnText: "Learn More",
    },
    {
      idx:"9",
      title: "Accessories",
      description: "",
      backgroundVideo: "",
      backgroundImg: "Accessoriess.jpg",
      leftBtnText: "Shop Now",
      rightBtnText: "",
    },
  ];

  export {carData,CarDetailData};
  